In [10]:
import pandas as pd

In [11]:
# Leer el archivo CSV
df = pd.read_csv("master_final.csv", encoding='utf-8')

In [12]:
# Imprimir cantidad de observaciones y variables
print(f"Número de filas: {len(df)}\nNúmero de columnas: {len(df.columns)}\n")

# Información general del DataFrame
print(df.info())

# Estadísticas descriptivas
print(df.describe())

Número de filas: 39999
Número de columnas: 15

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39999 entries, 0 to 39998
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   depreg   39999 non-null  int64
 1   mupreg   39999 non-null  int64
 2   mesreg   39999 non-null  int64
 3   añoreg   39999 non-null  int64
 4   diaocu   39999 non-null  int64
 5   mesocu   39999 non-null  int64
 6   añoocu   23725 non-null  float64
 7   depocu   39999 non-null  int64
 8   mupocu   39999 non-null  int64
 9   edadhom  39999 non-null  int64
 10  edadmuj  39999 non-null  int64
 11  grethom  7989 non-null   float64
 12  gretmuj  7989 non-null   float64
 13  nachom   39998 non-null  float64
 14  nacmuj   39998 non-null  float64
dtypes: float64(5), int64(10)
memory usage: 4.6 MB
None
             depreg        mupreg        mesreg        añoreg        diaocu  \
count  39999.000000  39999.000000  39999.000000  39999.000000  39999.000000
mean       7.554789    760.147554      6.536388   2013.897847     15.711968
std        7.096225    710.341560      3.375461      2.205744      8.687542
min        1.000000    101.000000      1.000000   2010.000000      1.000000
25%        1.000000    101.000000      4.000000   2012.000000      8.000000
50%        5.000000    506.000000      7.000000   2014.000000     16.000000
75%       13.000000   1301.000000      9.000000   2016.000000     23.000000
max       22.000000   2217.000000     12.000000   2018.000000     31.000000

             mesocu        añoocu        depocu        mupocu       edadhom  \
count  39999.000000  23725.000000  39999.000000  39999.000000  39999.000000
mean       6.298332   2014.104489      7.585215    762.974449    627.399860
std        3.243424      2.634415      7.080271    708.269617    469.130744
min        1.000000   2010.000000      1.000000    101.000000     15.000000
25%        3.000000   2011.000000      1.000000    101.000000     37.000000
50%        6.000000   2015.000000      5.000000    506.000000    999.000000
75%        9.000000   2016.000000     13.000000   1301.000000    999.000000
max       12.000000   2017.000000     22.000000   2217.000000    999.000000

            edadmuj      grethom      gretmuj        nachom        nacmuj
count  39999.000000  7989.000000  7989.000000  39998.000000  39998.000000
mean     622.586365     7.515334     7.550632    357.267988    357.447297
std      471.609227     2.920439     2.890567    575.329728    581.178454
min       14.000000     1.000000     1.000000     -1.000000     -1.000000
25%       33.000000     9.000000     9.000000    320.000000    320.000000
50%      999.000000     9.000000     9.000000    320.000000    320.000000
75%      999.000000     9.000000     9.000000    320.000000    320.000000
max      999.000000     9.000000     9.000000   9999.000000   9999.000000

In [13]:
for column in df.columns:
    print(f"{column}: {df[column].describe()}")
    print(f"Presenta entradas con NAN: {df[column].hasnans}")
    if df[column].hasnans:
        print(f"Cantidad de observaciones con NAN: {df[column].isna().sum()}")
    print("--------------------------------------------------------------------")

depreg: count    39999.000000
mean         7.554789
std          7.096225
min          1.000000
25%          1.000000
50%          5.000000
75%         13.000000
max         22.000000
Name: depreg, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
mupreg: count    39999.000000
mean       760.147554
std        710.341560
min        101.000000
25%        101.000000
50%        506.000000
75%       1301.000000
max       2217.000000
Name: mupreg, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
mesreg: count    39999.000000
mean         6.536388
std          3.375461
min          1.000000
25%          4.000000
50%          7.000000
75%          9.000000
max         12.000000
Name: mesreg, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
añoreg: count    39999.000000
mean      2013.897847
std          2.205744
min       2010.000000
25%       2012.000000
50%       2014.000000
75%       2016.000000
max       2018.000000
Name: añoreg, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
diaocu: count    39999.000000
mean        15.711968
std          8.687542
min          1.000000
25%          8.000000
50%         16.000000
75%         23.000000
max         31.000000
Name: diaocu, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
mesocu: count    39999.000000
mean         6.298332
std          3.243424
min          1.000000
25%          3.000000
50%          6.000000
75%          9.000000
max         12.000000
Name: mesocu, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
añoocu: count    23725.000000
mean      2014.104489
std          2.634415
min       2010.000000
25%       2011.000000
50%       2015.000000
75%       2016.000000
max       2017.000000
Name: añoocu, dtype: float64
Presenta entradas con NAN: True
Cantidad de observaciones con NAN: 16274
--------------------------------------------------------------------
depocu: count    39999.000000
mean         7.585215
std          7.080271
min          1.000000
25%          1.000000
50%          5.000000
75%         13.000000
max         22.000000
Name: depocu, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
mupocu: count    39999.000000
mean       762.974449
std        708.269617
min        101.000000
25%        101.000000
50%        506.000000
75%       1301.000000
max       2217.000000
Name: mupocu, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
edadhom: count    39999.000000
mean       627.399860
std        469.130744
min         15.000000
25%         37.000000
50%        999.000000
75%        999.000000
max        999.000000
Name: edadhom, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
edadmuj: count    39999.000000
mean       622.586365
std        471.609227
min         14.000000
25%         33.000000
50%        999.000000
75%        999.000000
max        999.000000
Name: edadmuj, dtype: float64
Presenta entradas con NAN: False
--------------------------------------------------------------------
grethom: count    7989.000000
mean        7.515334
std         2.920439
min         1.000000
25%         9.000000
50%         9.000000
75%         9.000000
max         9.000000
Name: grethom, dtype: float64
Presenta entradas con NAN: True
Cantidad de observaciones con NAN: 32010
--------------------------------------------------------------------
gretmuj: count    7989.000000
mean        7.550632
std         2.890567
min         1.000000
25%         9.000000
50%         9.000000
75%         9.000000
max         9.000000
Name: gretmuj, dtype: float64
Presenta entradas con NAN: True
Cantidad de observaciones con NAN: 32010
--------------------------------------------------------------------
nachom: count    39998.000000
mean       357.267988
std        575.329728
min         -1.000000
25%        320.000000
50%        320.000000
75%        320.000000
max       9999.000000
Name: nachom, dtype: float64
Presenta entradas con NAN: True
Cantidad de observaciones con NAN: 1
--------------------------------------------------------------------
nacmuj: count    39998.000000
mean       357.447297
std        581.178454
min         -1.000000
25%        320.000000
50%        320.000000
75%        320.000000
max       9999.000000
Name: nacmuj, dtype: float64
Presenta entradas con NAN: True
Cantidad de observaciones con NAN: 1
--------------------------------------------------------------------